server:
  port: ${LISTEN_PORT:8080}


clients:
  service-url: http://customer-service
  address: ${clients.service-url}
  identity: ${clients.service-url}

observability:
  global-application: customer-application
  tracing:
    enabled: true
    ratio : 0.1
    endpoint: ""

spring:
  application:
    name: api-service


management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metrics

  otlp:
    tracing:
      endpoint: ${observability.tracing.endpoint}/v1/traces
  tracing:
    enabled: ${observability.tracing.enabled}
    sampling:
      probability: ${observability.tracing.ratio}
