server.port: 8080

addressClient:
  baseUrl: http://customer-service:8081

customerClient:
  baseUrl: http://customer-service:8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-service

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans