server:
  port: ${LISTEN_PORT:8080}


clients:
  service-url: http://customer-service
  address: ${clients.service-url}
  identity: ${clients.service-url}

observability:
  global-application: customer-application
  tracing:
    enabled: true
    ratio : 0.1
    endpoint: ""
  metrics:
    endpoint: ""

spring:
  application:
    name: api-service


management:
  endpoint:
    prometheus:
      enabled: false
  endpoints:
    web:
      exposure:
        include: []

  otlp:
    tracing:
      endpoint: ${observability.tracing.endpoint}/v1/traces
    metrics:
      export:
        url: ${observability.metrics.endpoint}/v1/metrics
        resource-attributes:
          "service.name": ${spring.application.name}
  tracing:
    enabled: ${observability.tracing.enabled}
    sampling:
      probability: ${observability.tracing.ratio}
