server:
  port: ${LISTEN_PORT:8080}


clients:
  service-url: http://customer-service
  address: ${clients.service-url}
  identity: ${clients.service-url}

observability:
  global-application: customer-application
  tracing:
    enabled: true
    ratio : 0.1
    endpoint: ""

spring:
  application:
    name: api-service

  sleuth:
    enabled: ${observability.tracing.enabled}
    otel:
      config:
        trace-id-ratio-based: ${observability.tracing.ratio}
      exporter:
        otlp:
          enabled: ${observability.tracing.enabled}
          endpoint: ${observability.tracing.endpoint}
      resource:
        attributes:
          "application.name": ${observability.global-application}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metrics