server:
  port: ${LISTEN_PORT:8081}

business:
  customers:
    1:
      name: Mickey Mouse
      address: Flower Street, Mickeycity
    2:
      name: Donald Duck
      address: Anger road, Donaldcity
    3:
      name: Picsou
      address: Hill top, Donaldcity
    4:
      name: Gontran
      address: Lucky street, Donaldcity

observability:
  global-application: customer-application
  tracing:
    enabled: true
    ratio : 0.1
    endpoint: ""

spring:
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metrics
  endpoint:
    prometheus:
      enabled: true
  otlp:
    tracing:
      endpoint: ${observability.tracing.endpoint}/v1/traces

  tracing:
    enabled: ${observability.tracing.enabled}
    sampling:
      probability: ${observability.tracing.ratio}
