version: '3.9'

networks:
  observability_tutorial:
    external: true
    name: observability_tutorial

volumes:
  observability_tutorial:
    external: true
    name: observability_tutorial


services:
  grafana:
    image: grafana/grafana-oss:9.3.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - observability_tutorial
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo:1.5.0
    command: --config.file=/etc/tempo/config.yml
    volumes:
      - ./tempo:/etc/tempo:ro
    networks:
      - observability_tutorial
