apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    version: 1
    uid: tempo
    editable: true
    url: http://tempo:3100
    isDefault: false
    basicAuth: false
    apiVersion: 1
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        mapTagNamesEnabled: true
        mappedTags: [ { key: 'application.name', value: 'application' } ]
        tags:
          - application
        lokiSearch: true